[package]
    name = "minecraft"
    debug_build = true
    
[compiler]
    compiler = "g++"
	args = ["-fverbose-asm"]
	append_args = true

[linker]
	libraries = ["-lglfw", "-lvulkan"]

[misc]
	static_analysis_enabled = false

